// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RMS.Infrastructure;

#nullable disable

namespace RMS.Infrastructure.Migrations
{
    [DbContext(typeof(RMSDbContext))]
    [Migration("20250618191648_SeedData2")]
    partial class SeedData2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RMS.Core.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 14, DateTimeKind.Utc).AddTicks(5572),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Appetizers"
                        },
                        new
                        {
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 14, DateTimeKind.Utc).AddTicks(6992),
                            Description = "Main dishes including burgers and pizzas",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Main Dishes"
                        },
                        new
                        {
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 14, DateTimeKind.Utc).AddTicks(7183),
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Desserts"
                        },
                        new
                        {
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 14, DateTimeKind.Utc).AddTicks(7184),
                            Description = "Beverages including soft drinks and juices",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("RMS.Core.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("CouponId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            CouponId = 1,
                            Code = "HAPPYHOUR20",
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(4349),
                            DiscountPercentage = 20m,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            CouponId = 2,
                            Code = "BIGORDER10",
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(5459),
                            DiscountPercentage = 10m,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            CouponId = 3,
                            Code = "STUDENT10",
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(5462),
                            DiscountPercentage = 10m,
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            CouponId = 4,
                            Code = "SENIOR15",
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(5463),
                            DiscountPercentage = 15m,
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("RMS.Core.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("DailyOrderCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PreparationTimeInMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("MenuItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(2548),
                            DailyOrderCount = 0,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Spring Rolls",
                            PreparationTimeInMinutes = 0,
                            UnitPrice = 5.99m
                        },
                        new
                        {
                            MenuItemId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(3762),
                            DailyOrderCount = 0,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Caesar Salad",
                            PreparationTimeInMinutes = 0,
                            UnitPrice = 7.99m
                        },
                        new
                        {
                            MenuItemId = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(3765),
                            DailyOrderCount = 0,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Grilled Chicken",
                            PreparationTimeInMinutes = 0,
                            UnitPrice = 12.99m
                        },
                        new
                        {
                            MenuItemId = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(3766),
                            DailyOrderCount = 0,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Chocolate Cake",
                            PreparationTimeInMinutes = 0,
                            UnitPrice = 4.99m
                        },
                        new
                        {
                            MenuItemId = 5,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(3767),
                            DailyOrderCount = 0,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Coca Cola",
                            PreparationTimeInMinutes = 0,
                            UnitPrice = 1.99m
                        },
                        new
                        {
                            MenuItemId = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(3768),
                            DailyOrderCount = 0,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Cheesecake",
                            PreparationTimeInMinutes = 0,
                            UnitPrice = 6.50m
                        },
                        new
                        {
                            MenuItemId = 7,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(3769),
                            DailyOrderCount = 0,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Mango Juice",
                            PreparationTimeInMinutes = 0,
                            UnitPrice = 3.99m
                        },
                        new
                        {
                            MenuItemId = 8,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(3771),
                            DailyOrderCount = 0,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Spaghetti Carbonara",
                            PreparationTimeInMinutes = 0,
                            UnitPrice = 10.99m
                        },
                        new
                        {
                            MenuItemId = 9,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(3772),
                            DailyOrderCount = 0,
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Vegetable Stir Fry",
                            PreparationTimeInMinutes = 0,
                            UnitPrice = 8.99m
                        });
                });

            modelBuilder.Entity("RMS.Core.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("int");

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(8, 4)
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("Total")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("TotalBeforeDiscounts")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("CouponId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("TableId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(8748),
                            CustomerId = 1,
                            DiscountAmount = 0m,
                            IsDeleted = false,
                            Note = "No onions",
                            OrderStatus = 0,
                            OrderType = 0,
                            TableId = 1,
                            TaxPercentage = 0.085m,
                            Total = 20m,
                            TotalBeforeDiscounts = 20m
                        },
                        new
                        {
                            OrderId = 2,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(374),
                            CustomerId = 2,
                            DiscountAmount = 0m,
                            IsDeleted = false,
                            OrderStatus = 2,
                            OrderType = 1,
                            TaxPercentage = 0.085m,
                            Total = 15m,
                            TotalBeforeDiscounts = 15m
                        },
                        new
                        {
                            OrderId = 3,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(377),
                            CustomerId = 3,
                            DiscountAmount = 0m,
                            IsDeleted = false,
                            OrderStatus = 3,
                            OrderType = 2,
                            TaxPercentage = 0.085m,
                            Total = 30m,
                            TotalBeforeDiscounts = 30m
                        },
                        new
                        {
                            OrderId = 4,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(378),
                            CustomerId = 1,
                            DiscountAmount = 0m,
                            IsDeleted = false,
                            OrderStatus = 0,
                            OrderType = 0,
                            TaxPercentage = 0.085m,
                            Total = 20m,
                            TotalBeforeDiscounts = 20m
                        },
                        new
                        {
                            OrderId = 5,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(379),
                            CustomerId = 2,
                            DeliveryAddress = "123 Main St",
                            DiscountAmount = 0m,
                            IsDeleted = false,
                            Note = "Please ring the bell",
                            OrderStatus = 0,
                            OrderType = 2,
                            TaxPercentage = 0.085m,
                            Total = 22.5m,
                            TotalBeforeDiscounts = 25m
                        });
                });

            modelBuilder.Entity("RMS.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(1038),
                            IsDeleted = false,
                            MenuItemId = 1,
                            OrderId = 1,
                            Quantity = 2,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(1745),
                            IsDeleted = false,
                            MenuItemId = 3,
                            OrderId = 1,
                            Quantity = 1,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(1746),
                            IsDeleted = false,
                            MenuItemId = 2,
                            OrderId = 2,
                            Quantity = 1,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(1748),
                            IsDeleted = false,
                            MenuItemId = 5,
                            OrderId = 2,
                            Quantity = 2,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(1748),
                            IsDeleted = false,
                            MenuItemId = 4,
                            OrderId = 3,
                            Quantity = 1,
                            UnitPrice = 0m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(1749),
                            IsDeleted = false,
                            MenuItemId = 6,
                            OrderId = 3,
                            Quantity = 1,
                            UnitPrice = 0m
                        });
                });

            modelBuilder.Entity("RMS.Core.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<int>("ReservationStatus")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("TableId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(2168),
                            CustomerId = 2,
                            DurationInMinutes = 90,
                            IsDeleted = false,
                            NumberOfGuests = 2,
                            ReservationStatus = 1,
                            SpecialRequests = "Window seat please",
                            StartTime = new DateTime(2025, 6, 7, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            TableId = 2
                        },
                        new
                        {
                            ReservationId = 2,
                            AssignedStaffId = 6,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(3623),
                            CustomerId = 2,
                            DurationInMinutes = 90,
                            IsDeleted = false,
                            NumberOfGuests = 2,
                            ReservationStatus = 0,
                            SpecialRequests = "Quiet area",
                            StartTime = new DateTime(2025, 6, 7, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TableId = 2
                        },
                        new
                        {
                            ReservationId = 3,
                            AssignedStaffId = 5,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 16, DateTimeKind.Utc).AddTicks(3819),
                            CustomerId = 1,
                            DurationInMinutes = 60,
                            IsDeleted = false,
                            NumberOfGuests = 4,
                            ReservationStatus = 1,
                            SpecialRequests = "Window seat",
                            StartTime = new DateTime(2025, 6, 7, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            TableId = 1
                        });
                });

            modelBuilder.Entity("RMS.Core.Models.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Capacity = 4,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(4605),
                            IsAvailable = false,
                            IsDeleted = false,
                            TableNumber = 1
                        },
                        new
                        {
                            TableId = 2,
                            Capacity = 2,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(5373),
                            IsAvailable = false,
                            IsDeleted = false,
                            TableNumber = 2
                        },
                        new
                        {
                            TableId = 3,
                            Capacity = 6,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(5374),
                            IsAvailable = true,
                            IsDeleted = false,
                            TableNumber = 3
                        },
                        new
                        {
                            TableId = 4,
                            Capacity = 8,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(5375),
                            IsAvailable = true,
                            IsDeleted = false,
                            TableNumber = 4
                        });
                });

            modelBuilder.Entity("RMS.Core.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffPosition")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(6308),
                            Email = "aya.khaled@example.com",
                            HashedPassword = "123456",
                            IsDeleted = false,
                            PhoneNumber = "0100000001",
                            UserName = "Aya Khaled",
                            UserType = 0
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(7478),
                            Email = "doha.ezzat@example.com",
                            HashedPassword = "123456",
                            IsDeleted = false,
                            PhoneNumber = "0100000002",
                            UserName = "Doha Ezzat",
                            UserType = 0
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(7480),
                            Email = "jameela.abdulrahman@example.com",
                            HashedPassword = "123456",
                            IsDeleted = false,
                            PhoneNumber = "0100000003",
                            UserName = "Jameela Abdulrahman",
                            UserType = 0
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(7501),
                            Email = "shimaa.mohamed@example.com",
                            HashedPassword = "123456",
                            IsDeleted = false,
                            PhoneNumber = "0100000004",
                            UserName = "Shimaa Mohamed",
                            UserType = 0
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(7503),
                            Email = "karim.elshenawy@rms.com",
                            HashedPassword = "123456",
                            IsDeleted = false,
                            PhoneNumber = "0100000005",
                            StaffPosition = 0,
                            UserName = "Karim ElShenawy",
                            UserType = 1
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(7961),
                            Email = "laila.hassan@rms.com",
                            HashedPassword = "123456",
                            IsDeleted = false,
                            PhoneNumber = "0100000006",
                            StaffPosition = 1,
                            UserName = "Laila Hassan",
                            UserType = 1
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(7964),
                            Email = "mohamed.tarek@rms.com",
                            HashedPassword = "123456",
                            IsDeleted = false,
                            PhoneNumber = "0100000007",
                            StaffPosition = 2,
                            UserName = "Mohamed Tarek",
                            UserType = 1
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2025, 6, 18, 19, 16, 48, 15, DateTimeKind.Utc).AddTicks(7966),
                            Email = "sara.mostafa@rms.com",
                            HashedPassword = "123456",
                            IsDeleted = false,
                            PhoneNumber = "0100000008",
                            StaffPosition = 3,
                            UserName = "Sara Mostafa",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("RMS.Core.Models.Category", b =>
                {
                    b.HasOne("RMS.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("RMS.Core.Models.Coupon", b =>
                {
                    b.HasOne("RMS.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("RMS.Core.Models.MenuItem", b =>
                {
                    b.HasOne("RMS.Core.Models.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("RMS.Core.Models.Order", b =>
                {
                    b.HasOne("RMS.Core.Models.User", "AssignedStaff")
                        .WithMany("AssignedOrders")
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.Coupon", "Coupon")
                        .WithMany("UsedInOrders")
                        .HasForeignKey("CouponId");

                    b.HasOne("RMS.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "Customer")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Core.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");

                    b.HasOne("RMS.Core.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedStaff");

                    b.Navigation("Coupon");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("DeletedByUser");

                    b.Navigation("Table");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("RMS.Core.Models.OrderItem", b =>
                {
                    b.HasOne("RMS.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Core.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RMS.Core.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("MenuItem");

                    b.Navigation("Order");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("RMS.Core.Models.Reservation", b =>
                {
                    b.HasOne("RMS.Core.Models.User", "AssignedStaff")
                        .WithMany("AssignedReservations")
                        .HasForeignKey("AssignedStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "Customer")
                        .WithMany("CustomerReservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Core.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.Table", "Table")
                        .WithMany("Reservations")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RMS.Core.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedStaff");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Customer");

                    b.Navigation("DeletedByUser");

                    b.Navigation("Table");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("RMS.Core.Models.Table", b =>
                {
                    b.HasOne("RMS.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("RMS.Core.Models.User", b =>
                {
                    b.HasOne("RMS.Core.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RMS.Core.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("RMS.Core.Models.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("RMS.Core.Models.Coupon", b =>
                {
                    b.Navigation("UsedInOrders");
                });

            modelBuilder.Entity("RMS.Core.Models.MenuItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RMS.Core.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RMS.Core.Models.Table", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("RMS.Core.Models.User", b =>
                {
                    b.Navigation("AssignedOrders");

                    b.Navigation("AssignedReservations");

                    b.Navigation("CustomerOrders");

                    b.Navigation("CustomerReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
